### ISSUE TITLE
Generate Intellisense Lua file

### ISSUE THREAD

**Issue by Medik-GH** [EOP-Labs/M2TWEOP-library#14]
* Add Fynn's Luadocs.lua to the repo
* Figure out a way to automatically generate this file either with ldoc or with Fynn's script that is parsing the `index.html`

**Comment by FynnTW** [comment]
Closed with commit:
https://github.com/youneuoy/M2TWEOP-library/commit/dcc60daa38fbc881472c6fdac71cbf61907c7c5c
