### ISSUE TITLE
Update ImGUI Lua documentation to the same format as the normal Lua docs

### ISSUE THREAD

**Issue by Medik-GH** [EOP-Labs/M2TWEOP-library#30]
![image](https://user-images.githubusercontent.com/22448079/216839908-c2f21d47-7d62-4fa9-9f56-c71e3b49dc1a.png)

We don't want just code blocks and the this page being generated from a single .md file

Also try and document somewhere the contents of https://github.com/youneuoy/M2TWEOP-library/blob/master/M2TWEOP-luaPlugin/luaPlugin/imgui/sol_ImGui.h#L1758

**Comment by yaneay** [comment]
Started. Now need add documentation info to M2TWEOP-luaPlugin/luaPlugin/imgui/sol_ImGui.h
For testing purposes docs generating done via generateImGuiDocs.ps1 script

**Comment by Medik-GH** [comment]
> Started. Now need add documentation info to M2TWEOP-luaPlugin/luaPlugin/imgui/sol_ImGui.h For testing purposes docs generating done via generateImGuiDocs.ps1 script

Great stuff

**Comment by Medik-GH** [comment]
Completed by @FynnTW 🥳
