### ISSUE TITLE
Custom tile extended limit not working.

### ISSUE THREAD

**Issue by Karallius** [EOP-Labs/M2TWEOP-library#39]
my mod has been using the expanded limit of custom tiles for long now. vanilla allows 100, eop through lua allows more.

It was working fine and I did not change anything, though I've been updating eop in my mod frequently and it seems that this function stopped working at some point, but I only realized this now.

here is how it works:

I have a file called converter_custom_tiles.lua where many custom tiles are set (besides the ones in the vanilla file), like this:

```function addAndSetTiles()

    stratmap.objects.replaceTile("Helms-Deep_Province",167,158,"hornburg_amb.wfc","clear","midday");

    stratmap.objects.replaceTile("whatever1",161,193,"mine.wfc","clear","midday");

    stratmap.objects.replaceTile("whatever2",140,316,"mine.wfc","clear","midday");


end```

this file is is called by another file called cobertedFromOldEop.lua like this:

```require('Converted_custom_tiles')
require('Converted_stratForts')
require('Converted_stratModels')
require('Converted_stratPorts')

function setConvertedEntries()
    addAndSetTiles();
    addAndSetFortsModels();
    addAndSetStratModels();
    addAndSetPortsModels();
end
```

Here is the link for the mod:

https://www.moddb.com/mods/third-age-total-war-40/downloads/third-age-47-full-standalone-windows-only

**Comment by yaneay** [comment]
fixed
