### ISSUE TITLE
Crash when leaving the strategic map.

### ISSUE THREAD

**Issue by DinarMayor** [EOP-Labs/M2TWEOP-library#44]
The crash that occurs when exiting the strategy map to the main menu occurs every time you add units to the recruitment pool (addMercUnit) (whether from EDU or EOP). The same crash occurs if you change the binding to religion (setMercReligion). But this crash is not there after restarting the game. The failure is stable, it happens, both on the disk version and on the Steam version too. Program version 2.1.39 and earlier. 
[report-Dinar-6004-23_03_18.txt](https://github.com/youneuoy/M2TWEOP-library/files/11007659/report-Dinar-6004-23_03_18.txt)
![!!!!!!!!!_](https://user-images.githubusercontent.com/110694287/226088936-8b50e464-b368-4157-96ca-6424a237f2b4.jpg)

**Comment by yaneay** [comment]
@FynnTW

**Comment by DinarMayor** [comment]
Crash also occurs during a settlement has rebelled.

**Comment by FynnTW** [comment]
Fixed
