### ISSUE TITLE
Crash when give the city through a diplomat.

### ISSUE THREAD

**Issue by DinarMayor** [EOP-Labs/M2TWEOP-library#45]
Sometimes when transferring a city through a diplomat, mercenaries are created in it. Crash occurs if the game tries to spawn mercenaries (addMercUnit) in the given city.
Game log entry:
`17:22:27.242 [data.invalid] [error] World creation error: couldn't find unit description for unit type 'Mercenary Crossbowmen'.
17:22:40.738 [system.rpt] [error]`
![1](https://user-images.githubusercontent.com/110694287/227782114-58b206a9-c5b5-48f5-9789-d0c9426aa859.jpg)
![4](https://user-images.githubusercontent.com/110694287/227782227-b6da1be5-49ce-48b7-b80d-723259220557.jpg)
[report-Dinar-4744-23_03_26.txt](https://github.com/youneuoy/M2TWEOP-library/files/11071857/report-Dinar-4744-23_03_26.txt)

**Comment by yaneay** [comment]
@FynnTW

**Comment by DinarMayor** [comment]
Crash also occurs during a settlement has rebelled.

**Comment by FynnTW** [comment]
please test this after next eop release

**Comment by DinarMayor** [comment]
Yes OK.
