### ISSUE TITLE
setCharacterModel doesn't fire when using models from descr_strat_models

### ISSUE THREAD

**Issue by Medik-GH** [EOP-Labs/M2TWEOP-library#48]
`ourCharacter:setCharacterModel("saruman");` does not work if Saruman is coming from the descr_strat_models file
`ourCharacter:setCharacterModel("saruman");` does work if Saruman is added via https://youneuoy.github.io/M2TWEOP-library/_static/LuaLib/index.html#objects.addCharacterCas

**Comment by FynnTW** [comment]
https://github.com/youneuoy/M2TWEOP-library/commit/9852a64328b760df1076884a2ea41910f72e645c fixed with this
