### ISSUE TITLE
stratmap model change under fog is not working

### ISSUE THREAD

**Issue by Karallius** [EOP-Labs/M2TWEOP-library#53]
check minas tirith and osgiliath are loading the wrong models
yet the eop feature is set as you can see in the minimap (the dots)
![0000](https://user-images.githubusercontent.com/126305995/236531927-59b70c76-751d-493e-8ed8-e3e51f489786.jpg)
ee

**Comment by Medik-GH** [comment]
Write your EOP version.

**Comment by Karallius** [comment]
latest released version
2.2.0 with the hotfix

**Comment by DinarMayor** [comment]
In vanilla it is also displayed incorrectly, without EOP, I met this. For example, a village is displayed under the fog, when in fact there is a large city. It's not because of the program most likely.

**Comment by Karallius** [comment]
This is a well known vanilla problem
The point is that yaneay included a fix for it in the latest version of eop, and its not working anymore.

**Comment by DinarMayor** [comment]
Some models that are in the fog may remain normal. The task was to timely change those models that are in the player's field of vision and thereby get rid of the crash associated with this problem. And this was done.

**Comment by Karallius** [comment]
Then there is some misunderstanding happening cause the conversation I had with yaneay was different.
