### ISSUE TITLE
Add event "onCharacterMarriesPrincess" 

### ISSUE THREAD

**Issue by DinarMayor** [EOP-Labs/M2TWEOP-library#6]
The **onCharacterMarries** function does not work when marrying princesses - it only works with regular wives from the family tree. There are two separate events for princesses in medieval2:
-for ordinary women
 `CharacterMarries`
-for princesses
`CharacterMarriesPrincess`
![Скриншот 05-08-2022 224436](https://user-images.githubusercontent.com/110694287/183149895-f0d30a6a-709c-439f-a998-06100b85e133.jpg)

**Comment by yaneay** [comment]
@Callistonian 🥳

**Comment by yaneay** [comment]
i think we can export `CharacterMarriesPrincess` m2tw event to lua also as `onCharacterMarries`, not `onCharacterMarriesPrincess`. So we have 1 ok-working function, not 2

**Comment by Callistonian** [comment]
I've added an event function for onCharacterMarriesPrincess(). I do not suggest combining these two events as they monitor different things and there would be no way to tell if the character married a princess agent or just another off-map bride. This is an important distinction in scripts I've written in the past.
