### ISSUE TITLE
Latest release (M2TWEOP-3.0.4) seems to crash on launch for latest version of SSHIP (0.98)

### ISSUE THREAD

**Issue by tryingtokeepup** [EOP-Labs/M2TWEOP-library#68]
Issue is non-existent for previous versions of EOP + SSHIP.

Will try to debug myself but might be beyond my lua/c++ understanding.

**Comment by FynnTW** [comment]
please be more helpful

put 
[misc]
bug_report = true

in your mod config and then provide the text file inside med2/reports

**Comment by FynnTW** [comment]
you might need to increase the building levels limit in luaPluginScript.lua
