### ISSUE TITLE
Config option 'Disable launch of mod without EOP enabled' is not working correctly

### ISSUE THREAD

**Issue by Medik-GH** [EOP-Labs/M2TWEOP-library#8]
**Description**

`isBlockLaunchWithoutEop` is the config option. 

Even with this enabled and EOP disabled, the mod still starts when it shouldn't. 

**Goal**
With the config option enabled in the UI and EOP disabled in the UI, the mod should fail to start with some message as to why.

**Comment by yaneay** [comment]
> Even with this enabled and EOP disabled, the mod still starts when it shouldn't.

for this option modder must edit edu file in some way.

**Comment by yaneay** [comment]
@EddieEldridge , here: https://github.com/youneuoy/M2TWEOP-library/blob/d1443c848a8ea004b330b4038419071b432b6408/M2TWEOP%20Code/M2TWEOP%20library/Injects.cpp#L3078
all **type** records must be replaced with **eopOnlyType**. With this option enabled eop recognize this records, but vanilla game - not

**Comment by Medik-GH** [comment]
**Resolution:**

Update https://youneuoy.github.io/M2TWEOP-library/M2TWEOP_LAUNCHER_SETTINGS.html to mention that in order for this option to work, you need to edit your vanilla EDU such that it has a unit with the type of `eopOnlyType`.

Provide an example of this in the documentation

**Comment by Medik-GH** [comment]
The documentation has been updated to more clearly explain this option.
